### PR TITLE
One last thing! Built the files into objects instead of strings for further optimization

### PR DESCRIPTION
**Pull request by piercemoore**
This is the last one for a bit, I promise :D you merged about 30 seconds before I committed this.

### CODE REVIEW

**Comment by cif** [comment]
At a quick glance this looks great.  I have absolutely no reservations or issues whatsoever with the re factor, in fact I couldn't be happier about it.  Your optimizations are 100% welcome, I'll make sure to credit you when I update the readme and publish to NPM.  I'm going to implement a lot of what you've done here in a couple other places... so THANK YOU!

**Comment by cif** [comment]
Updated NPM and the readme/package.  I was running node 0.6 it looks like you're using some nice/new-to-me fs methods. I didn't have them available until updating node, so I changed package to require node >= 0.8

Cheers!

**Comment by piercemoore** [comment]
Awesome! You're quite welcome. I'm very eager to see if you notice any performance improvements with this refactor. 

And I really appreciate the credit! Always nice to get the old name out there, especially attached to a module as kickass as this one. 

I'm not going to lie to you, I'm considering what it would take to have this module do whatever other microtemplating framework you could throw at it, like mustache, ember, etc. Most likely wouldn't take much. I'll look into it :D Are you pretty much rolling this module into Flint?

**Comment by cif** [comment]
I started a project last summer (http://hello.theflybook.com) which in its early stages was stitching the coffee/templates/stylus together with a few different modules I gathered around the web.  When my directories/file sizes started getting big, I wrote handlebar-rider out of necessity - hence the quick but functional hack.  Then, I started running up against limitations with the coffeescript compiler I was using (https://github.com/serpentem/coffee-toaster) so I decided it was time to buck up and bundle it.  Also made some pretty nice DRY features / core classes for client side apps.

Long story short, I didn't think anyone was going to get super excited about HBR though I did take the time to package it, so late last summer it became "plater.js" in Flint.  Since then, I've had a a few people check it out and a couple use it.  You're the first to actually contribute. 

Moving forward, my hope is to have Flint's compile tools run on by well tuned modules.   I kinda like the name Plater better than Handlebar-Rider.  What are your thoughts on taking over this module and making it available on NPM as "plater"?  It speaks to the same thought you had about making it work with other languages (jade and eco were next on my list)  At this point, it's more yours anyway.  The only thing I would ask is that I like my the green/yellow/red output to the console, can you make that an option or the default?

Sorry to write an essay there, let me know what you think

**Comment by piercemoore** [comment]
Nice essay! :-P 

That sounds like a lot of fun! I'd love to put some more work into this and make it a kick ass jack-of-all-trades template compiler and perhaps even moving rapidly toward a no-application-structure-required, a la carte web application helper that does templates, SASS/LESS, linting, the works. That was my main draw to this module in the first place, was that it didn't require me to have a specific setup or structure or whatever in order to use it. It just WORKS. You tell it where to look and where to put stuff, and it just fucking works. And I think you were on to something there and I also think with a little bit of elbow grease we can make something that ends up being a must-have tool for developers.

So yeah. Let's fucking do it!

And with the console colors, I will actually add in a method to SuperCLI that will allow a developer to display a message with a certain color, no strings attached. Matter of fact, I'll do that right now. Then I'll push up some changes that will let that reflect in HBR. 

So I guess the awkward question is this: would you make me a collaborator on this project so that I can stop having to bug you every time I want to push up changes? :-P And I'm not sure how NPM does collaboration, but I feel like it would make it more convenient to be able to push updates to NPM as well.

I like where this is headed!

**Comment by cif** [comment]
Added you as collab on github, it looks like I can add an owner to the repo for NPM https://npmjs.org/doc/owner.html

Just need to know your username there, before we get any further with that... 

You down to rename this thing?  I'd been using "Plater" within flint. That name seems to speak more to our goal of offering multiple template languages that offer precompiling ability via node.

Added you to flint as well (likely preemptively), but certainly wouldn't mind if you wanted to have a look and see how I've started cobbling together these custom compilers.  Have a look at the flint.js (configuration) file first, then node/flint.js (the CLI script) and you'll get the idea pretty quickly

**Comment by piercemoore** [comment]
Awesome!! My username on npm is also "piercemoore" https://npmjs.org/~piercemoore

I am totally cool naming it plater, I dig that name. I can't help but think that we should just create a new repo instead of renaming this one. Renaming a node module with a large installed user base is a terrible, terrible thing to do. All of a sudden nobody can update via NPM and people get mad and whatnot. So my vote is that you create a new repo called Plater and we can start from scratch!

I'll definitely take a look at that shortly and see if I can get my head wrapped around it. The really difficult part is getting the file tree built out. Once we have that, we know how to parse/compile things and where to put them. Makes things pretty easy :-P

**Pull request merged**
