### PR TITLE
Urgent: Package.json fix for fatal install bug

### PR DESCRIPTION
**Pull request by piercemoore**
Because I'm a fucking moron and didn't include the dependencies in package.json when I submitted my last pull request. I already had these node modules installed globally and it didn't throw any errors for me because of that, but installing handlebar-rider on a fresh folder threw multiple dependency failures because I failed to update package.json.

Sorry :-/

**EDIT:** Yeah... Because of a HUGE logic error that I just found, templates were actually being returned as empty strings no matter what. I have fixed that bug (that I caused) and it's here in this pull request as well.

### CODE REVIEW

**Comment by cif** [comment]
Not sure that empty string bug was your fault. Ran into the same thing yesterday. Merged quick for ya mor when I'm back in front of a real computer

**Comment by piercemoore** [comment]
A
wesome, thank you so much! I've been freaking out over here. Lol :-/

And how about you just let me take the fall for this one and we'll just
accept that I kinda boned this one :-P

Talk to you soon. Async branch coming today, get excited!

## 

_Pierce Moore_
m 214-616-7264
Linkedin.com/in/PierceMoore

**Comment by cif** [comment]
FYI Just published the latest to changes to NPM + handlebar-rider@0.1.13

Pumped to see how async improves compiling performance.  Handlebars isn't too bad with a lot of files (142 in my big project), however I also wrote a custom coffeescript compiler with the same namespacing conventions which at only 87 files is taking about 1.5s / 2s to compile after a change is registered by fs.watch()

Keep me posted!

**Comment by piercemoore** [comment]
Posted: Pull request #8 :)

**Pull request merged**
